language: cpp
# Need to run on the Trusty Beta Platform for custom PPA (Qt 5.6)
sudo: required
dist: trusty

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: QStickyButton
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
    - GH_REPO_REF: github.com/vidavidorra/QStickyButton.git

# Install dependencies
addons:
  apt:
    packages:
      - graphviz
      - doxygen
      - doxygen-latex
      - doxygen-doc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gcc-5 g++-5 qt56base

before_script:
  - /opt/qt56/bin/qmake --version
  - gcc-5 --version
  - g++-5 --version
  - doxygen --version

# Build
script:
  - source /opt/qt56/bin/qt56-env.sh
  - mkdir build && cd build
  - /opt/qt56/bin/qmake QMAKE_CC=gcc-5 QMAKE_CXX=g++-5 ../QStickyButton.pro
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
